CREATE TABLE REGISTRATIONS 
(
  DEVICE_TOKEN VARCHAR2(360 CHAR) NOT NULL 
, DEVICE_MODEL VARCHAR2(30 CHAR) NOT NULL 
, USER_ID VARCHAR2(120 CHAR) 
, SENDER_ID VARCHAR2(40 CHAR) 
, APPLICATION_ID VARCHAR2(120 CHAR) NOT NULL 
, CONSTRAINT REGISTRATIONS_PK PRIMARY KEY 
  (
    DEVICE_TOKEN 
  )
  ENABLE 
); 

CREATE TABLE TOKENS 
(
  DEVICE_TOKEN VARCHAR2(360 CHAR) NOT NULL 
, APPLICATION_ID VARCHAR2(120 CHAR) NOT NULL 
, FEATURE_ID VARCHAR2(30 CHAR) NOT NULL 
, TOKEN_COUNT NUMBER 
, CONSTRAINT TOKENS_PK PRIMARY KEY 
  (
    DEVICE_TOKEN 
  , APPLICATION_ID 
  , FEATURE_ID 
  )
  ENABLE 
);

ALTER TABLE TOKENS
ADD CONSTRAINT TOKENS_REGISTRATIONS_FK1 FOREIGN KEY
(
  DEVICE_TOKEN 
)
REFERENCES REGISTRATIONS
(
  DEVICE_TOKEN 
)
ON DELETE CASCADE ENABLE;

commit;