package model;

import java.util.ArrayList;
import java.util.List;

public class ThematicMapUSACitiesDataList {

    private static List<ThematicMapUSACitiesData> s_dataList = null;

    public ThematicMapUSACitiesDataList() {
        if (s_dataList == null) {
            s_dataList = new ArrayList<ThematicMapUSACitiesData>();
            s_dataList.add(new ThematicMapUSACitiesData("MO_COLUMBIA","Columbia",26));
            s_dataList.add(new ThematicMapUSACitiesData("OK_OKLAHOMA_CITY","Oklahoma City",75));
            s_dataList.add(new ThematicMapUSACitiesData("MN_SAINT_PAUL","Saint Paul",47));
            s_dataList.add(new ThematicMapUSACitiesData("MI_DETROIT","Detroit",94));
            s_dataList.add(new ThematicMapUSACitiesData("GA_SAVANNAH","Savannah",25));
            s_dataList.add(new ThematicMapUSACitiesData("CT_STAMFORD","Stamford",11));
            s_dataList.add(new ThematicMapUSACitiesData("WY_CHEYENNE","Cheyenne",88));
            s_dataList.add(new ThematicMapUSACitiesData("FL_HOLLYWOOD","Hollywood",39));
            s_dataList.add(new ThematicMapUSACitiesData("CA_TORRANCE","Torrance",65));
            s_dataList.add(new ThematicMapUSACitiesData("AK_ANCHORAGE","Anchorage",58));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SACRAMENTO","Sacramento",91));
            s_dataList.add(new ThematicMapUSACitiesData("TX_AUSTIN","Austin",99));
            s_dataList.add(new ThematicMapUSACitiesData("AZ_MESA","Mesa",60));
            s_dataList.add(new ThematicMapUSACitiesData("OR_GRESHAM","Gresham",27));
            s_dataList.add(new ThematicMapUSACitiesData("CO_COLORADO_SPRINGS","Colorado Springs",41));
            s_dataList.add(new ThematicMapUSACitiesData("NC_HIGH_POINT","High Point",39));
            s_dataList.add(new ThematicMapUSACitiesData("FL_MIAMI_GARDENS","Miami Gardens",93));
            s_dataList.add(new ThematicMapUSACitiesData("AZ_PHOENIX","Phoenix",91));
            s_dataList.add(new ThematicMapUSACitiesData("TX_LAREDO","Laredo",19));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SANTA_CLARA","Santa Clara",94));
            s_dataList.add(new ThematicMapUSACitiesData("CA_NORWALK","Norwalk",35));
            s_dataList.add(new ThematicMapUSACitiesData("FL_PEMBROKE_PINES","Pembroke Pines",9));
            s_dataList.add(new ThematicMapUSACitiesData("TX_LEWISVILLE","Lewisville",68));
            s_dataList.add(new ThematicMapUSACitiesData("TX_CARROLLTON","Carrollton",54));
            s_dataList.add(new ThematicMapUSACitiesData("TX_RICHARDSON","Richardson",1));
            s_dataList.add(new ThematicMapUSACitiesData("CO_LAKEWOOD","Lakewood",14));
            s_dataList.add(new ThematicMapUSACitiesData("TX_GRAND_PRAIRIE","Grand Prairie",69));
            s_dataList.add(new ThematicMapUSACitiesData("NV_RENO","Reno",5));
            s_dataList.add(new ThematicMapUSACitiesData("CA_FONTANA","Fontana",44));
            s_dataList.add(new ThematicMapUSACitiesData("NM_SANTA_FE","Santa Fe",46));
            s_dataList.add(new ThematicMapUSACitiesData("CO_ARVADA","Arvada",77));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SALINAS","Salinas",10));
            s_dataList.add(new ThematicMapUSACitiesData("CA_OXNARD","Oxnard",56));
            s_dataList.add(new ThematicMapUSACitiesData("CA_OAKLAND","Oakland",96));
            s_dataList.add(new ThematicMapUSACitiesData("CA_RIVERSIDE","Riverside",63));
            s_dataList.add(new ThematicMapUSACitiesData("PA_PHILADELPHIA","Philadelphia",37));
            s_dataList.add(new ThematicMapUSACitiesData("MN_MINNEAPOLIS","Minneapolis",72));
            s_dataList.add(new ThematicMapUSACitiesData("KS_OLATHE","Olathe",54));
            s_dataList.add(new ThematicMapUSACitiesData("TN_MEMPHIS","Memphis",11));
            s_dataList.add(new ThematicMapUSACitiesData("AL_MONTGOMERY","Montgomery",43));
            s_dataList.add(new ThematicMapUSACitiesData("CA_PASADENA","Pasadena",90));
            s_dataList.add(new ThematicMapUSACitiesData("WI_MADISON","Madison",82));
            s_dataList.add(new ThematicMapUSACitiesData("MI_ANN_ARBOR","Ann Arbor",14));
            s_dataList.add(new ThematicMapUSACitiesData("CA_GLENDALE","Glendale",75));
            s_dataList.add(new ThematicMapUSACitiesData("NY_SYRACUSE","Syracuse",66));
            s_dataList.add(new ThematicMapUSACitiesData("FL_MIAMI","Miami",12));
            s_dataList.add(new ThematicMapUSACitiesData("OH_COLUMBUS","Columbus",16));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SANTA_CLARITA","Santa Clarita",42));
            s_dataList.add(new ThematicMapUSACitiesData("AK_JUNEAU","Juneau",24));
            s_dataList.add(new ThematicMapUSACitiesData("KY_LEXINGTON","Lexington",93));
            s_dataList.add(new ThematicMapUSACitiesData("CA_ANAHEIM","Anaheim",37));
            s_dataList.add(new ThematicMapUSACitiesData("CA_FREMONT","Fremont",82));
            s_dataList.add(new ThematicMapUSACitiesData("WA_OLYMPIA","Olympia",15));
            s_dataList.add(new ThematicMapUSACitiesData("CA_EL_MONTE","El Monte",69));
            s_dataList.add(new ThematicMapUSACitiesData("IN_INDIANAPOLIS","Indianapolis",83));
            s_dataList.add(new ThematicMapUSACitiesData("IL_SPRINGFIELD","Springfield",84));
            s_dataList.add(new ThematicMapUSACitiesData("LA_SHREVEPORT","Shreveport",76));
            s_dataList.add(new ThematicMapUSACitiesData("OK_NORMAN","Norman",73));
            s_dataList.add(new ThematicMapUSACitiesData("NC_RALEIGH","Raleigh",2));
            s_dataList.add(new ThematicMapUSACitiesData("IA_CEDAR_RAPIDS","Cedar Rapids",98));
            s_dataList.add(new ThematicMapUSACitiesData("LA_LAFAYETTE","Lafayette",8));
            s_dataList.add(new ThematicMapUSACitiesData("IL_AURORA","Aurora",36));
            s_dataList.add(new ThematicMapUSACitiesData("VA_NORFOLK","Norfolk",79));
            s_dataList.add(new ThematicMapUSACitiesData("TX_WICHITA_FALLS","Wichita Falls",63));
            s_dataList.add(new ThematicMapUSACitiesData("TN_KNOXVILLE","Knoxville",15));
            s_dataList.add(new ThematicMapUSACitiesData("ND_BISMARCK","Bismarck",94));
            s_dataList.add(new ThematicMapUSACitiesData("AZ_PEORIA","Peoria",25));
            s_dataList.add(new ThematicMapUSACitiesData("NC_GREENSBORO","Greensboro",33));
            s_dataList.add(new ThematicMapUSACitiesData("CO_THORNTON","Thornton",3));
            s_dataList.add(new ThematicMapUSACitiesData("WA_SEATTLE","Seattle",3));
            s_dataList.add(new ThematicMapUSACitiesData("CA_MORENO_VALLEY","Moreno Valley",75));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SANTA_ANA","Santa Ana",83));
            s_dataList.add(new ThematicMapUSACitiesData("CA_RANCHO_CUCAMONGA","Rancho Cucamonga",23));
            s_dataList.add(new ThematicMapUSACitiesData("NC_FAYETTEVILLE","Fayetteville",86));
            s_dataList.add(new ThematicMapUSACitiesData("PA_HARRISBURG","Harrisburg",78));
            s_dataList.add(new ThematicMapUSACitiesData("CA_VICTORVILLE","Victorville",70));
            s_dataList.add(new ThematicMapUSACitiesData("FL_CAPE_CORAL","Cape Coral",7));
            s_dataList.add(new ThematicMapUSACitiesData("MI_GRAND_RAPIDS","Grand Rapids",97));
            s_dataList.add(new ThematicMapUSACitiesData("WI_MILWAUKEE","Milwaukee",22));
            s_dataList.add(new ThematicMapUSACitiesData("OK_TULSA","Tulsa",94));
            s_dataList.add(new ThematicMapUSACitiesData("RI_PROVIDENCE","Providence",74));
            s_dataList.add(new ThematicMapUSACitiesData("ME_AUGUSTA","Augusta",63));
            s_dataList.add(new ThematicMapUSACitiesData("TX_ARLINGTON","Arlington",34));
            s_dataList.add(new ThematicMapUSACitiesData("CO_PUEBLO","Pueblo",97));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SAN_JOSE","San Jose",81));
            s_dataList.add(new ThematicMapUSACitiesData("CA_LANCASTER","Lancaster",11));
            s_dataList.add(new ThematicMapUSACitiesData("CA_VISALIA","Visalia",15));
            s_dataList.add(new ThematicMapUSACitiesData("CA_HUNTINGTON_BEACH","Huntington Beach",16));
            s_dataList.add(new ThematicMapUSACitiesData("KY_FRANKFORT","Frankfort",24));
            s_dataList.add(new ThematicMapUSACitiesData("TX_PASADENA","Pasadena",87));
            s_dataList.add(new ThematicMapUSACitiesData("UT_SALT_LAKE_CITY","Salt Lake City",42));
            s_dataList.add(new ThematicMapUSACitiesData("NY_NEW_YORK","New York",92));
            s_dataList.add(new ThematicMapUSACitiesData("TX_KILLEEN","Killeen",25));
            s_dataList.add(new ThematicMapUSACitiesData("AZ_GLENDALE","Glendale",67));
            s_dataList.add(new ThematicMapUSACitiesData("VA_RICHMOND","Richmond",79));
            s_dataList.add(new ThematicMapUSACitiesData("MD_BALTIMORE","Baltimore",38));
            s_dataList.add(new ThematicMapUSACitiesData("CA_ROSEVILLE","Roseville",72));
            s_dataList.add(new ThematicMapUSACitiesData("CA_ELK_GROVE","Elk Grove",25));
            s_dataList.add(new ThematicMapUSACitiesData("MA_LOWELL","Lowell",2));
            s_dataList.add(new ThematicMapUSACitiesData("TX_WACO","Waco",0));
            s_dataList.add(new ThematicMapUSACitiesData("AL_MOBILE","Mobile",82));
            s_dataList.add(new ThematicMapUSACitiesData("TX_BROWNSVILLE","Brownsville",54));
            s_dataList.add(new ThematicMapUSACitiesData("SD_PIERRE","Pierre",92));
            s_dataList.add(new ThematicMapUSACitiesData("CA_GARDEN_GROVE","Garden Grove",25));
            s_dataList.add(new ThematicMapUSACitiesData("VA_ALEXANDRIA","Alexandria",40));
            s_dataList.add(new ThematicMapUSACitiesData("TX_BEAUMONT","Beaumont",46));
            s_dataList.add(new ThematicMapUSACitiesData("CA_STOCKTON","Stockton",94));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SANTA_ROSA","Santa Rosa",73));
            s_dataList.add(new ThematicMapUSACitiesData("IA_DAVENPORT","Davenport",43));
            s_dataList.add(new ThematicMapUSACitiesData("CT_NEW_HAVEN","New Haven",32));
            s_dataList.add(new ThematicMapUSACitiesData("FL_FORT_LAUDERDALE","Fort Lauderdale",82));
            s_dataList.add(new ThematicMapUSACitiesData("MO_JEFFERSON_CITY","Jefferson City",73));
            s_dataList.add(new ThematicMapUSACitiesData("MN_ST__PAUL","St. Paul",89));
            s_dataList.add(new ThematicMapUSACitiesData("IL_ROCKFORD","Rockford",2));
            s_dataList.add(new ThematicMapUSACitiesData("CA_HAYWARD","Hayward",18));
            s_dataList.add(new ThematicMapUSACitiesData("TX_HOUSTON","Houston",12));
            s_dataList.add(new ThematicMapUSACitiesData("OH_DAYTON","Dayton",83));
            s_dataList.add(new ThematicMapUSACitiesData("KS_WICHITA","Wichita",53));
            s_dataList.add(new ThematicMapUSACitiesData("CA_FAIRFIELD","Fairfield",11));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SAN_FRANCISCO","San Francisco",2));
            s_dataList.add(new ThematicMapUSACitiesData("IL_JOLIET","Joliet",17));
            s_dataList.add(new ThematicMapUSACitiesData("CA_POMONA","Pomona",52));
            s_dataList.add(new ThematicMapUSACitiesData("TX_GARLAND","Garland",54));
            s_dataList.add(new ThematicMapUSACitiesData("MS_JACKSON","Jackson",14));
            s_dataList.add(new ThematicMapUSACitiesData("NC_WINSTON_SALEM","Winston-Salem",71));
            s_dataList.add(new ThematicMapUSACitiesData("AL_BIRMINGHAM","Birmingham",85));
            s_dataList.add(new ThematicMapUSACitiesData("CA_CHULA_VISTA","Chula Vista",48));
            s_dataList.add(new ThematicMapUSACitiesData("NY_YONKERS","Yonkers",36));
            s_dataList.add(new ThematicMapUSACitiesData("OH_CLEVELAND","Cleveland",96));
            s_dataList.add(new ThematicMapUSACitiesData("MA_WORCESTER","Worcester",87));
            s_dataList.add(new ThematicMapUSACitiesData("LA_NEW_ORLEANS","New Orleans",79));
            s_dataList.add(new ThematicMapUSACitiesData("MI_WARREN","Warren",77));
            s_dataList.add(new ThematicMapUSACitiesData("NY_ROCHESTER","Rochester",90));
            s_dataList.add(new ThematicMapUSACitiesData("FL_CLEARWATER","Clearwater",87));
            s_dataList.add(new ThematicMapUSACitiesData("CA_PALMDALE","Palmdale",8));
            s_dataList.add(new ThematicMapUSACitiesData("CA_INGLEWOOD","Inglewood",52));
            s_dataList.add(new ThematicMapUSACitiesData("TX_CORPUS_CHRISTI","Corpus Christi",45));
            s_dataList.add(new ThematicMapUSACitiesData("MI_LANSING","Lansing",66));
            s_dataList.add(new ThematicMapUSACitiesData("NE_LINCOLN","Lincoln",19));
            s_dataList.add(new ThematicMapUSACitiesData("TX_MESQUITE","Mesquite",70));
            s_dataList.add(new ThematicMapUSACitiesData("OR_PORTLAND","Portland",13));
            s_dataList.add(new ThematicMapUSACitiesData("FL_MIRAMAR","Miramar",8));
            s_dataList.add(new ThematicMapUSACitiesData("TX_DENTON","Denton",69));
            s_dataList.add(new ThematicMapUSACitiesData("WI_GREEN_BAY","Green Bay",69));
            s_dataList.add(new ThematicMapUSACitiesData("MD_ANNAPOLIS","Annapolis",21));
            s_dataList.add(new ThematicMapUSACitiesData("MO_INDEPENDENCE","Independence",39));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SAN_BERNARDINO","San Bernardino",21));
            s_dataList.add(new ThematicMapUSACitiesData("FL_PALM_BAY","Palm Bay",89));
            s_dataList.add(new ThematicMapUSACitiesData("TX_DALLAS","Dallas",43));
            s_dataList.add(new ThematicMapUSACitiesData("NJ_ELIZABETH","Elizabeth",33));
            s_dataList.add(new ThematicMapUSACitiesData("KY_LOUISVILLE","Louisville",91));
            s_dataList.add(new ThematicMapUSACitiesData("FL_HIALEAH","Hialeah",65));
            s_dataList.add(new ThematicMapUSACitiesData("WV_CHARLESTON","Charleston",90));
            s_dataList.add(new ThematicMapUSACitiesData("HI_HONOLULU","Honolulu",42));
            s_dataList.add(new ThematicMapUSACitiesData("CA_COSTA_MESA","Costa Mesa",8));
            s_dataList.add(new ThematicMapUSACitiesData("CA_ANTIOCH","Antioch",57));
            s_dataList.add(new ThematicMapUSACitiesData("CA_CONCORD","Concord",14));
            s_dataList.add(new ThematicMapUSACitiesData("TX_MIDLAND","Midland",43));
            s_dataList.add(new ThematicMapUSACitiesData("FL_TAMPA","Tampa",40));
            s_dataList.add(new ThematicMapUSACitiesData("AZ_TUCSON","Tucson",82));
            s_dataList.add(new ThematicMapUSACitiesData("IL_PEORIA","Peoria",58));
            s_dataList.add(new ThematicMapUSACitiesData("NY_ALBANY","Albany",85));
            s_dataList.add(new ThematicMapUSACitiesData("IL_ELGIN","Elgin",39));
            s_dataList.add(new ThematicMapUSACitiesData("CA_CORONA","Corona",91));
            s_dataList.add(new ThematicMapUSACitiesData("TN_CHATTANOOGA","Chattanooga",28));
            s_dataList.add(new ThematicMapUSACitiesData("DC_WASHINGTON","Washington",23));
            s_dataList.add(new ThematicMapUSACitiesData("PA_ERIE","Erie",2));
            s_dataList.add(new ThematicMapUSACitiesData("CA_VENTURA","Ventura",89));
            s_dataList.add(new ThematicMapUSACitiesData("MA_SPRINGFIELD","Springfield",5));
            s_dataList.add(new ThematicMapUSACitiesData("IL_CHICAGO","Chicago",41));
            s_dataList.add(new ThematicMapUSACitiesData("CT_BRIDGEPORT","Bridgeport",79));
            s_dataList.add(new ThematicMapUSACitiesData("CO_DENVER","Denver",45));
            s_dataList.add(new ThematicMapUSACitiesData("MA_CAMBRIDGE","Cambridge",57));
            s_dataList.add(new ThematicMapUSACitiesData("VA_VIRGINIA_BEACH","Virginia Beach",16));
            s_dataList.add(new ThematicMapUSACitiesData("DE_DOVER","Dover",98));
            s_dataList.add(new ThematicMapUSACitiesData("VA_NEWPORT_NEWS","Newport News",22));
            s_dataList.add(new ThematicMapUSACitiesData("OH_AKRON","Akron",89));
            s_dataList.add(new ThematicMapUSACitiesData("UT_WEST_VALLEY_CITY","West Valley City",84));
            s_dataList.add(new ThematicMapUSACitiesData("TN_CLARKSVILLE","Clarksville",13));
            s_dataList.add(new ThematicMapUSACitiesData("NV_LAS_VEGAS","Las Vegas",55));
            s_dataList.add(new ThematicMapUSACitiesData("TX_LUBBOCK","Lubbock",29));
            s_dataList.add(new ThematicMapUSACitiesData("TN_MURFREESBORO","Murfreesboro",48));
            s_dataList.add(new ThematicMapUSACitiesData("TN_NASHVILLE","Nashville",47));
            s_dataList.add(new ThematicMapUSACitiesData("CO_FORT_COLLINS","Fort Collins",62));
            s_dataList.add(new ThematicMapUSACitiesData("PA_PITTSBURGH","Pittsburgh",3));
            s_dataList.add(new ThematicMapUSACitiesData("NJ_PATERSON","Paterson",38));
            s_dataList.add(new ThematicMapUSACitiesData("CA_FULLERTON","Fullerton",14));
            s_dataList.add(new ThematicMapUSACitiesData("MI_FLINT","Flint",21));
            s_dataList.add(new ThematicMapUSACitiesData("CO_WESTMINSTER","Westminster",41));
            s_dataList.add(new ThematicMapUSACitiesData("TX_MCKINNEY","McKinney",90));
            s_dataList.add(new ThematicMapUSACitiesData("OR_SALEM","Salem",57));
            s_dataList.add(new ThematicMapUSACitiesData("AZ_SCOTTSDALE","Scottsdale",92));
            s_dataList.add(new ThematicMapUSACitiesData("NH_CONCORD","Concord",37));
            s_dataList.add(new ThematicMapUSACitiesData("IN_EVANSVILLE","Evansville",95));
            s_dataList.add(new ThematicMapUSACitiesData("AR_LITTLE_ROCK","Little Rock",25));
            s_dataList.add(new ThematicMapUSACitiesData("NV_CARSON_CITY","Carson City",87));
            s_dataList.add(new ThematicMapUSACitiesData("CA_BURBANK","Burbank",98));
            s_dataList.add(new ThematicMapUSACitiesData("CO_AURORA","Aurora",76));
            s_dataList.add(new ThematicMapUSACitiesData("NJ_JERSEY_CITY","Jersey City",79));
            s_dataList.add(new ThematicMapUSACitiesData("WA_TACOMA","Tacoma",25));
            s_dataList.add(new ThematicMapUSACitiesData("IA_DES_MOINES","Des Moines",61));
            s_dataList.add(new ThematicMapUSACitiesData("MT_BILLINGS","Billings",32));
            s_dataList.add(new ThematicMapUSACitiesData("WA_BELLEVUE","Bellevue",12));
            s_dataList.add(new ThematicMapUSACitiesData("OR_EUGENE","Eugene",2));
            s_dataList.add(new ThematicMapUSACitiesData("OH_TOLEDO","Toledo",17));
            s_dataList.add(new ThematicMapUSACitiesData("WA_VANCOUVER","Vancouver",21));
            s_dataList.add(new ThematicMapUSACitiesData("IN_SOUTH_BEND","South Bend",44));
            s_dataList.add(new ThematicMapUSACitiesData("SC_CHARLESTON","Charleston",44));
            s_dataList.add(new ThematicMapUSACitiesData("NC_WILMINGTON","Wilmington",68));
            s_dataList.add(new ThematicMapUSACitiesData("TX_ROUND_ROCK","Round Rock",20));
            s_dataList.add(new ThematicMapUSACitiesData("MN_ROCHESTER","Rochester",49));
            s_dataList.add(new ThematicMapUSACitiesData("AZ_TEMPE","Tempe",44));
            s_dataList.add(new ThematicMapUSACitiesData("FL_CORAL_SPRINGS","Coral Springs",98));
            s_dataList.add(new ThematicMapUSACitiesData("LA_BATON_ROUGE","Baton Rouge",89));
            s_dataList.add(new ThematicMapUSACitiesData("AZ_CHANDLER","Chandler",78));
            s_dataList.add(new ThematicMapUSACitiesData("PA_ALLENTOWN","Allentown",76));
            s_dataList.add(new ThematicMapUSACitiesData("NC_CHARLOTTE","Charlotte",57));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SAN_DIEGO","San Diego",68));
            s_dataList.add(new ThematicMapUSACitiesData("NC_DURHAM","Durham",29));
            s_dataList.add(new ThematicMapUSACitiesData("NV_NORTH_LAS_VEGAS","North Las Vegas",52));
            s_dataList.add(new ThematicMapUSACitiesData("CA_WEST_COVINA","West Covina",80));
            s_dataList.add(new ThematicMapUSACitiesData("VA_ARLINGTON","Arlington",8));
            s_dataList.add(new ThematicMapUSACitiesData("TX_ABILENE","Abilene",6));
            s_dataList.add(new ThematicMapUSACitiesData("CA_ORANGE","Orange",23));
            s_dataList.add(new ThematicMapUSACitiesData("TX_AMARILLO","Amarillo",37));
            s_dataList.add(new ThematicMapUSACitiesData("KS_TOPEKA","Topeka",67));
            s_dataList.add(new ThematicMapUSACitiesData("NM_ALBUQUERQUE","Albuquerque",11));
            s_dataList.add(new ThematicMapUSACitiesData("CA_VALLEJO","Vallejo",76));
            s_dataList.add(new ThematicMapUSACitiesData("GA_ATLANTA","Atlanta",96));
            s_dataList.add(new ThematicMapUSACitiesData("SC_COLUMBIA","Columbia",55));
            s_dataList.add(new ThematicMapUSACitiesData("GA_AUGUSTA","Augusta",74));
            s_dataList.add(new ThematicMapUSACitiesData("CA_LONG_BEACH","Long Beach",68));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SUNNYVALE","Sunnyvale",84));
            s_dataList.add(new ThematicMapUSACitiesData("ID_BOISE","Boise",7));
            s_dataList.add(new ThematicMapUSACitiesData("IN_FORT_WAYNE","Fort Wayne",32));
            s_dataList.add(new ThematicMapUSACitiesData("FL_ST__PETERSBURG","St. Petersburg",56));
            s_dataList.add(new ThematicMapUSACitiesData("IL_NAPERVILLE","Naperville",26));
            s_dataList.add(new ThematicMapUSACitiesData("CA_OCEANSIDE","Oceanside",50));
            s_dataList.add(new ThematicMapUSACitiesData("CA_DALY_CITY","Daly City",52));
            s_dataList.add(new ThematicMapUSACitiesData("UT_PROVO","Provo",17));
            s_dataList.add(new ThematicMapUSACitiesData("MT_HELENA","Helena",15));
            s_dataList.add(new ThematicMapUSACitiesData("FL_JACKSONVILLE","Jacksonville",82));
            s_dataList.add(new ThematicMapUSACitiesData("NJ_TRENTON","Trenton",40));
            s_dataList.add(new ThematicMapUSACitiesData("NJ_NEWARK","Newark",13));
            s_dataList.add(new ThematicMapUSACitiesData("CA_BAKERSFIELD","Bakersfield",10));
            s_dataList.add(new ThematicMapUSACitiesData("FL_ORLANDO","Orlando",60));
            s_dataList.add(new ThematicMapUSACitiesData("FL_POMPANO_BEACH","Pompano Beach",32));
            s_dataList.add(new ThematicMapUSACitiesData("MO_KANSAS_CITY","Kansas City",9));
            s_dataList.add(new ThematicMapUSACitiesData("KS_KANSAS_CITY","Kansas City",53));
            s_dataList.add(new ThematicMapUSACitiesData("CA_RICHMOND","Richmond",87));
            s_dataList.add(new ThematicMapUSACitiesData("FL_TALLAHASSEE","Tallahassee",23));
            s_dataList.add(new ThematicMapUSACitiesData("UT_WEST_JORDAN","West Jordan",95));
            s_dataList.add(new ThematicMapUSACitiesData("NY_BUFFALO","Buffalo",3));
            s_dataList.add(new ThematicMapUSACitiesData("KS_OVERLAND_PARK","Overland Park",91));
            s_dataList.add(new ThematicMapUSACitiesData("FL_GAINESVILLE","Gainesville",58));
            s_dataList.add(new ThematicMapUSACitiesData("CA_ONTARIO","Ontario",88));
            s_dataList.add(new ThematicMapUSACitiesData("TX_MCALLEN","McAllen",21));
            s_dataList.add(new ThematicMapUSACitiesData("VA_HAMPTON","Hampton",19));
            s_dataList.add(new ThematicMapUSACitiesData("GA_ATHENS","Athens",43));
            s_dataList.add(new ThematicMapUSACitiesData("CA_THOUSAND_OAKS","Thousand Oaks",3));
            s_dataList.add(new ThematicMapUSACitiesData("CT_HARTFORD","Hartford",18));
            s_dataList.add(new ThematicMapUSACitiesData("NH_MANCHESTER","Manchester",51));
            s_dataList.add(new ThematicMapUSACitiesData("CA_MODESTO","Modesto",74));
            s_dataList.add(new ThematicMapUSACitiesData("TX_PLANO","Plano",30));
            s_dataList.add(new ThematicMapUSACitiesData("NV_HENDERSON","Henderson",14));
            s_dataList.add(new ThematicMapUSACitiesData("CA_SIMI_VALLEY","Simi Valley",48));
            s_dataList.add(new ThematicMapUSACitiesData("CA_FRESNO","Fresno",45));
            s_dataList.add(new ThematicMapUSACitiesData("CA_DOWNEY","Downey",66));
            s_dataList.add(new ThematicMapUSACitiesData("TX_FORT_WORTH","Fort Worth",20));
            s_dataList.add(new ThematicMapUSACitiesData("OH_CINCINNATI","Cincinnati",18));
            s_dataList.add(new ThematicMapUSACitiesData("TX_SAN_ANTONIO","San Antonio",4));
            s_dataList.add(new ThematicMapUSACitiesData("VA_PORTSMOUTH","Portsmouth",77));
            s_dataList.add(new ThematicMapUSACitiesData("MA_BOSTON","Boston",43));
            s_dataList.add(new ThematicMapUSACitiesData("WA_SPOKANE","Spokane",17));
            s_dataList.add(new ThematicMapUSACitiesData("SD_SIOUX_FALLS","Sioux Falls",82));
            s_dataList.add(new ThematicMapUSACitiesData("AZ_GILBERT","Gilbert",34));
            s_dataList.add(new ThematicMapUSACitiesData("CA_IRVINE","Irvine",41));
            s_dataList.add(new ThematicMapUSACitiesData("MO_SPRINGFIELD","Springfield",78));
            s_dataList.add(new ThematicMapUSACitiesData("CA_LOS_ANGELES","Los Angeles",4));
            s_dataList.add(new ThematicMapUSACitiesData("MI_STERLING_HEIGHTS","Sterling Heights",48));
            s_dataList.add(new ThematicMapUSACitiesData("GA_COLUMBUS","Columbus",67));
            s_dataList.add(new ThematicMapUSACitiesData("CT_WATERBURY","Waterbury",63));
            s_dataList.add(new ThematicMapUSACitiesData("CA_BERKELEY","Berkeley",18));
            s_dataList.add(new ThematicMapUSACitiesData("TX_IRVING","Irving",69));
            s_dataList.add(new ThematicMapUSACitiesData("VT_MONTPELIER","Montpelier",39));
            s_dataList.add(new ThematicMapUSACitiesData("CA_ESCONDIDO","Escondido",13));
            s_dataList.add(new ThematicMapUSACitiesData("AL_HUNTSVILLE","Huntsville",25));
            s_dataList.add(new ThematicMapUSACitiesData("FL_PORT_ST__LUCIE","Port St. Lucie",41));
            s_dataList.add(new ThematicMapUSACitiesData("NC_CARY","Cary",72));
            s_dataList.add(new ThematicMapUSACitiesData("MO_ST__LOUIS","St. Louis",72));
            s_dataList.add(new ThematicMapUSACitiesData("NE_OMAHA","Omaha",23));
            s_dataList.add(new ThematicMapUSACitiesData("TX_EL_PASO","El Paso",62));
            s_dataList.add(new ThematicMapUSACitiesData("VA_CHESAPEAKE","Chesapeake",22));
        }
    }

    public List<ThematicMapUSACitiesData> getThematicMapUSACitiesData() {
        return s_dataList;
    }

    public int getThematicMapUSACitiesDataCount() {
        return s_dataList.size();
    }
}
