package model;

import java.util.ArrayList;
import java.util.List;

public class ThematicMapWorldCitiesDataList {

    private static List<ThematicMapWorldCitiesData> s_dataList = null;

    public ThematicMapWorldCitiesDataList() {
        if (s_dataList == null) {
            s_dataList = new ArrayList<ThematicMapWorldCitiesData>();
            s_dataList.add(new ThematicMapWorldCitiesData("USA_SAN_DIEGO","San Diego",88));
            s_dataList.add(new ThematicMapWorldCitiesData("IND_BANGALORE","Bangalore",0));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_CHICAGO","Chicago",35));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_SAO_PAULO","Sao Paulo",30));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_CAMPINAS","Campinas",26));
            s_dataList.add(new ThematicMapWorldCitiesData("SYR_DAMASCUS","Damascus",22));
            s_dataList.add(new ThematicMapWorldCitiesData("OMN_MUSCAT","Muscat",57));
            s_dataList.add(new ThematicMapWorldCitiesData("CAF_BANGUI","Bangui",85));
            s_dataList.add(new ThematicMapWorldCitiesData("BHR_MANAMA","Manama",42));
            s_dataList.add(new ThematicMapWorldCitiesData("MOZ_MAPUTO","Maputo",74));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_CURITIBA","Curitiba",69));
            s_dataList.add(new ThematicMapWorldCitiesData("ERI_ASMARA","Asmara",95));
            s_dataList.add(new ThematicMapWorldCitiesData("CHN_SHENZHEN","Shenzhen",58));
            s_dataList.add(new ThematicMapWorldCitiesData("ITA_ROME","Rome",92));
            s_dataList.add(new ThematicMapWorldCitiesData("CHN_SHENYANG","Shenyang",10));
            s_dataList.add(new ThematicMapWorldCitiesData("CUB_HAVANA","Havana",33));
            s_dataList.add(new ThematicMapWorldCitiesData("CYP_NICOSIA","Nicosia",31));
            s_dataList.add(new ThematicMapWorldCitiesData("HTI_PORT_AU_PRINCE","Port-au-Prince",10));
            s_dataList.add(new ThematicMapWorldCitiesData("IND_AHMEDABAD","Ahmedabad",63));
            s_dataList.add(new ThematicMapWorldCitiesData("IND_MUMBAI","Mumbai",78));
            s_dataList.add(new ThematicMapWorldCitiesData("BGR_SOFIA","Sofia",78));
            s_dataList.add(new ThematicMapWorldCitiesData("MNE_PODGORICA","Podgorica",95));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_RECIFE","Recife",43));
            s_dataList.add(new ThematicMapWorldCitiesData("CHE_ZURICH","Zurich",27));
            s_dataList.add(new ThematicMapWorldCitiesData("TZA_DODOMA","Dodoma",43));
            s_dataList.add(new ThematicMapWorldCitiesData("NOR_OSLO","Oslo",78));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_ATLANTA","Atlanta",51));
            s_dataList.add(new ThematicMapWorldCitiesData("CIV_YAMOUSSOUKRO","Yamoussoukro",29));
            s_dataList.add(new ThematicMapWorldCitiesData("TJK_DUSHANBE","Dushanbe",84));
            s_dataList.add(new ThematicMapWorldCitiesData("UZB_TASHKENT","Tashkent",7));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_LOS_ANGELES","Los Angeles",0));
            s_dataList.add(new ThematicMapWorldCitiesData("NGA_PORT_HARCOURT","Port Harcourt",25));
            s_dataList.add(new ThematicMapWorldCitiesData("SDN_KHARTOUM","Khartoum",95));
            s_dataList.add(new ThematicMapWorldCitiesData("VEN_CARACAS","Caracas",24));
            s_dataList.add(new ThematicMapWorldCitiesData("MEX_PUEBLA","Puebla",14));
            s_dataList.add(new ThematicMapWorldCitiesData("BDI_BUJUMBURA","Bujumbura",95));
            s_dataList.add(new ThematicMapWorldCitiesData("PAK_LAHORE","Lahore",91));
            s_dataList.add(new ThematicMapWorldCitiesData("GNQ_MALABO","Malabo",40));
            s_dataList.add(new ThematicMapWorldCitiesData("ANT_WILLEMSTAD","Willemstad",14));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_MIAMI","Miami",67));
            s_dataList.add(new ThematicMapWorldCitiesData("GBR_WEST_YORKSHIRE","West Yorkshire",85));
            s_dataList.add(new ThematicMapWorldCitiesData("ZAF_PORT_ELIZABETH","Port Elizabeth",13));
            s_dataList.add(new ThematicMapWorldCitiesData("AZE_BAKU","Baku",37));
            s_dataList.add(new ThematicMapWorldCitiesData("UKR_KHARKIV","Kharkiv",16));
            s_dataList.add(new ThematicMapWorldCitiesData("RUS_KAZAN","Kazan",16));
            s_dataList.add(new ThematicMapWorldCitiesData("NGA_ZARIA","Zaria",39));
            s_dataList.add(new ThematicMapWorldCitiesData("MLI_BAMAKO","Bamako",6));
            s_dataList.add(new ThematicMapWorldCitiesData("ITA_MILAN","Milan",34));
            s_dataList.add(new ThematicMapWorldCitiesData("ABW_ORANJESTAD","Oranjestad",47));
            s_dataList.add(new ThematicMapWorldCitiesData("BEN_PORTO_NOVO","Porto-Novo",63));
            s_dataList.add(new ThematicMapWorldCitiesData("GUY_GEORGETOWN","Georgetown",54));
            s_dataList.add(new ThematicMapWorldCitiesData("COL_MEDELLIN","Medellin",64));
            s_dataList.add(new ThematicMapWorldCitiesData("AFG_KABUL","Kabul",10));
            s_dataList.add(new ThematicMapWorldCitiesData("MMR_NAYPYIDAW","Naypyidaw",88));
            s_dataList.add(new ThematicMapWorldCitiesData("NZL_WELLINGTON","Wellington",65));
            s_dataList.add(new ThematicMapWorldCitiesData("UKR_DNIPROPETROVSK","Dnipropetrovsk",97));
            s_dataList.add(new ThematicMapWorldCitiesData("BEN_COTONOU","Cotonou",65));
            s_dataList.add(new ThematicMapWorldCitiesData("BOL_LA_PAZ","La Paz",97));
            s_dataList.add(new ThematicMapWorldCitiesData("GHA_ACCRA","Accra",38));
            s_dataList.add(new ThematicMapWorldCitiesData("COL_BOGOTA","Bogota",83));
            s_dataList.add(new ThematicMapWorldCitiesData("NLD_AMSTERDAM","Amsterdam",9));
            s_dataList.add(new ThematicMapWorldCitiesData("AGO_LUANDA","Luanda",32));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_PITTSBURGH","Pittsburgh",56));
            s_dataList.add(new ThematicMapWorldCitiesData("ITA_NAPLES","Naples",49));
            s_dataList.add(new ThematicMapWorldCitiesData("HRV_ZAGREB","Zagreb",59));
            s_dataList.add(new ThematicMapWorldCitiesData("FIN_HELSINKI","Helsinki",79));
            s_dataList.add(new ThematicMapWorldCitiesData("MAR_CASABLANCA","Casablanca",72));
            s_dataList.add(new ThematicMapWorldCitiesData("ZAF_CAPE_TOWN","Cape Town",23));
            s_dataList.add(new ThematicMapWorldCitiesData("RUS_ROSTOV_ON_DON","Rostov-on-Don",84));
            s_dataList.add(new ThematicMapWorldCitiesData("SVK_BRATISLAVA","Bratislava",63));
            s_dataList.add(new ThematicMapWorldCitiesData("EST_TALLINN","Tallinn",12));
            s_dataList.add(new ThematicMapWorldCitiesData("LBY_BANGHAZI","Banghazi",79));
            s_dataList.add(new ThematicMapWorldCitiesData("VNM_HANOI","Hanoi",42));
            s_dataList.add(new ThematicMapWorldCitiesData("YEM_ADEN","Aden",59));
            s_dataList.add(new ThematicMapWorldCitiesData("YEM_SANA_A","Sana'a",47));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_SEATTLE","Seattle",7));
            s_dataList.add(new ThematicMapWorldCitiesData("KHM_PHNOM_PENH","Phnom Penh",35));
            s_dataList.add(new ThematicMapWorldCitiesData("IMN_DOUGLAS","Douglas",56));
            s_dataList.add(new ThematicMapWorldCitiesData("AUS_CANBERRA","Canberra",62));
            s_dataList.add(new ThematicMapWorldCitiesData("FLK_STANLEY","Stanley",25));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_DENVER","Denver",97));
            s_dataList.add(new ThematicMapWorldCitiesData("PRT_PORTO","Porto",83));
            s_dataList.add(new ThematicMapWorldCitiesData("JOR_AMMAN","Amman",73));
            s_dataList.add(new ThematicMapWorldCitiesData("VEN_MARACAIBO","Maracaibo",6));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_DALLAS","Dallas",33));
            s_dataList.add(new ThematicMapWorldCitiesData("PAK_KARACHI","Karachi",22));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_FORTALEZA","Fortaleza",30));
            s_dataList.add(new ThematicMapWorldCitiesData("FRA_PARIS","Paris",35));
            s_dataList.add(new ThematicMapWorldCitiesData("UGA_KAMPALA","Kampala",45));
            s_dataList.add(new ThematicMapWorldCitiesData("RUS_UFA","Ufa",36));
            s_dataList.add(new ThematicMapWorldCitiesData("TKM_ASHGABAT","Ashgabat",25));
            s_dataList.add(new ThematicMapWorldCitiesData("HKG_HONG_KONG","Hong Kong",52));
            s_dataList.add(new ThematicMapWorldCitiesData("MDA_CHISINAU","Chisinau",19));
            s_dataList.add(new ThematicMapWorldCitiesData("ISL_REYKJAVIK","Reykjavik",45));
            s_dataList.add(new ThematicMapWorldCitiesData("QAT_AL_DOHA","Al-Doha",73));
            s_dataList.add(new ThematicMapWorldCitiesData("SWZ_MBABANE","Mbabane",11));
            s_dataList.add(new ThematicMapWorldCitiesData("RUS_SAINT_PETERSBURG","Saint Petersburg",43));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_MINNEAPOLIS","Minneapolis",18));
            s_dataList.add(new ThematicMapWorldCitiesData("PRY_ASUNCION","Asuncion",98));
            s_dataList.add(new ThematicMapWorldCitiesData("BEL_BRUSSELS","Brussels",76));
            s_dataList.add(new ThematicMapWorldCitiesData("JPN_TOKYO","Tokyo",77));
            s_dataList.add(new ThematicMapWorldCitiesData("AND_ANDORRA_LA_VELLA","Andorra la Vella",97));
            s_dataList.add(new ThematicMapWorldCitiesData("SWE_STOCKHOLM","Stockholm",8));
            s_dataList.add(new ThematicMapWorldCitiesData("MRT_NOUAKCHOTT","Nouakchott",1));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_RIVERSIDE_SAN_BERNARDINO","Riverside-San Bernardino",50));
            s_dataList.add(new ThematicMapWorldCitiesData("DEU_BERLIN","Berlin",15));
            s_dataList.add(new ThematicMapWorldCitiesData("ARG_BUENOS_AIRES","Buenos Aires",1));
            s_dataList.add(new ThematicMapWorldCitiesData("FRA_LYON","Lyon",29));
            s_dataList.add(new ThematicMapWorldCitiesData("BLR_MINSK","Minsk",98));
            s_dataList.add(new ThematicMapWorldCitiesData("AUT_VIENNA","Vienna",96));
            s_dataList.add(new ThematicMapWorldCitiesData("PHL_MANILA","Manila",76));
            s_dataList.add(new ThematicMapWorldCitiesData("LKA_SRI_JAYAWARDENAPURA_KOTTE","Sri Jayawardenapura Kotte",52));
            s_dataList.add(new ThematicMapWorldCitiesData("TCD_N_DJAMENA","N'Djamena",41));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_PHOENIX","Phoenix",90));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_SALVADOR","Salvador",84));
            s_dataList.add(new ThematicMapWorldCitiesData("NGA_IBADAN","Ibadan",89));
            s_dataList.add(new ThematicMapWorldCitiesData("CMR_YAOUNDE","Yaounde",82));
            s_dataList.add(new ThematicMapWorldCitiesData("ZWE_HARARE","Harare",9));
            s_dataList.add(new ThematicMapWorldCitiesData("URY_MONTEVIDEO","Montevideo",19));
            s_dataList.add(new ThematicMapWorldCitiesData("DEU_MUNICH","Munich",33));
            s_dataList.add(new ThematicMapWorldCitiesData("SEN_DAKAR","Dakar",6));
            s_dataList.add(new ThematicMapWorldCitiesData("BLZ_BELMOPAN","Belmopan",89));
            s_dataList.add(new ThematicMapWorldCitiesData("KWT_KUWAIT_CITY","Kuwait City",67));
            s_dataList.add(new ThematicMapWorldCitiesData("SMR_SAN_MARINO","San Marino",82));
            s_dataList.add(new ThematicMapWorldCitiesData("NAM_WINDHOEK","Windhoek",69));
            s_dataList.add(new ThematicMapWorldCitiesData("TZA_DAR_ES_SALAAM","Dar es Salaam",96));
            s_dataList.add(new ThematicMapWorldCitiesData("COG_BRAZZAVILLE","Brazzaville",22));
            s_dataList.add(new ThematicMapWorldCitiesData("SUR_PARAMARIBO","Paramaribo",38));
            s_dataList.add(new ThematicMapWorldCitiesData("CHN_SHANGHAI","Shanghai",39));
            s_dataList.add(new ThematicMapWorldCitiesData("BRN_BANDAR_SERI_BEGAWAN","Bandar Seri Begawan",58));
            s_dataList.add(new ThematicMapWorldCitiesData("IRL_DUBLIN","Dublin",11));
            s_dataList.add(new ThematicMapWorldCitiesData("MEX_GUADALAJARA","Guadalajara",50));
            s_dataList.add(new ThematicMapWorldCitiesData("ARM_YEREVAN","Yerevan",79));
            s_dataList.add(new ThematicMapWorldCitiesData("TUN_TUNIS","Tunis",72));
            s_dataList.add(new ThematicMapWorldCitiesData("MLT_VALLETTA","Valletta",15));
            s_dataList.add(new ThematicMapWorldCitiesData("KOR_SEOUL","Seoul",14));
            s_dataList.add(new ThematicMapWorldCitiesData("ITA_TURIN","Turin",65));
            s_dataList.add(new ThematicMapWorldCitiesData("FJI_SUVA","Suva",20));
            s_dataList.add(new ThematicMapWorldCitiesData("ZAF_JOHANNESBURG_EKURHULENI","Johannesburg-Ekurhuleni",70));
            s_dataList.add(new ThematicMapWorldCitiesData("ROU_BUCHAREST","Bucharest",14));
            s_dataList.add(new ThematicMapWorldCitiesData("NIC_MANAGUA","Managua",86));
            s_dataList.add(new ThematicMapWorldCitiesData("PAN_PANAMA_CITY","Panama City",96));
            s_dataList.add(new ThematicMapWorldCitiesData("ZAF_VEREENIGING","Vereeniging",58));
            s_dataList.add(new ThematicMapWorldCitiesData("NER_NIAMEY","Niamey",83));
            s_dataList.add(new ThematicMapWorldCitiesData("BIH_SARAJEVO","Sarajevo",15));
            s_dataList.add(new ThematicMapWorldCitiesData("IND_HYDERABAD","Hyderabad",94));
            s_dataList.add(new ThematicMapWorldCitiesData("JPN_NAGOYA","Nagoya",0));
            s_dataList.add(new ThematicMapWorldCitiesData("TLS_DILI","Dili",41));
            s_dataList.add(new ThematicMapWorldCitiesData("BOL_SUCRE","Sucre",44));
            s_dataList.add(new ThematicMapWorldCitiesData("DEU_COLOGNE","Cologne",62));
            s_dataList.add(new ThematicMapWorldCitiesData("ZMB_LUSAKA","Lusaka",4));
            s_dataList.add(new ThematicMapWorldCitiesData("TUR_ISTANBUL","Istanbul",91));
            s_dataList.add(new ThematicMapWorldCitiesData("JPN_OSAKA","Osaka",57));
            s_dataList.add(new ThematicMapWorldCitiesData("GGY_ST__PETER_PORT","St. Peter Port",75));
            s_dataList.add(new ThematicMapWorldCitiesData("MEX_MONTERREY","Monterrey",86));
            s_dataList.add(new ThematicMapWorldCitiesData("GHA_KUMASI","Kumasi",46));
            s_dataList.add(new ThematicMapWorldCitiesData("SVN_LJUBLJANA","Ljubljana",85));
            s_dataList.add(new ThematicMapWorldCitiesData("ALB_TIRANA","Tirana",78));
            s_dataList.add(new ThematicMapWorldCitiesData("HUN_BUDAPEST","Budapest",43));
            s_dataList.add(new ThematicMapWorldCitiesData("RUS_MOSCOW","Moscow",35));
            s_dataList.add(new ThematicMapWorldCitiesData("JAM_KINGSTON","Kingston",29));
            s_dataList.add(new ThematicMapWorldCitiesData("HND_TEGUCIGALPA","Tegucigalpa",52));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_TAMPA","Tampa",79));
            s_dataList.add(new ThematicMapWorldCitiesData("NLD_ROTTERDAM","Rotterdam",84));
            s_dataList.add(new ThematicMapWorldCitiesData("PNG_PORT_MORESBY","Port Moresby",84));
            s_dataList.add(new ThematicMapWorldCitiesData("MNG_ULAN_BATOR","Ulan Bator",7));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_BOSTON","Boston",59));
            s_dataList.add(new ThematicMapWorldCitiesData("ESP_MADRID","Madrid",48));
            s_dataList.add(new ThematicMapWorldCitiesData("IND_CHENNAI","Chennai",59));
            s_dataList.add(new ThematicMapWorldCitiesData("ECU_QUITO","Quito",25));
            s_dataList.add(new ThematicMapWorldCitiesData("GBR_BIRMINGHAM","Birmingham",83));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_NEW_YORK","New York",60));
            s_dataList.add(new ThematicMapWorldCitiesData("LBN_BEIRUT","Beirut",77));
            s_dataList.add(new ThematicMapWorldCitiesData("KEN_NAIROBI","Nairobi",12));
            s_dataList.add(new ThematicMapWorldCitiesData("UKR_KIEV","Kiev",89));
            s_dataList.add(new ThematicMapWorldCitiesData("IRN_TEHRAN","Tehran",47));
            s_dataList.add(new ThematicMapWorldCitiesData("IDN_JAKARTA","Jakarta",36));
            s_dataList.add(new ThematicMapWorldCitiesData("RUS_NIZHNIY_NOVGOROD","Nizhniy Novgorod",11));
            s_dataList.add(new ThematicMapWorldCitiesData("PRK_PYONGYANG","Pyongyang",19));
            s_dataList.add(new ThematicMapWorldCitiesData("CHN_BEIJING","Beijing",48));
            s_dataList.add(new ThematicMapWorldCitiesData("GRC_ATHENS","Athens",92));
            s_dataList.add(new ThematicMapWorldCitiesData("TGO_LOME","Lome",6));
            s_dataList.add(new ThematicMapWorldCitiesData("MEX_MEXICO_CITY","Mexico City",70));
            s_dataList.add(new ThematicMapWorldCitiesData("NGA_ABUJA","Abuja",77));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_RIO_DE_JANEIRO","Rio de Janeiro",68));
            s_dataList.add(new ThematicMapWorldCitiesData("ZAF_PRETORIA","Pretoria",12));
            s_dataList.add(new ThematicMapWorldCitiesData("CHN_WUHAN","Wuhan",87));
            s_dataList.add(new ThematicMapWorldCitiesData("PER_LIMA","Lima",57));
            s_dataList.add(new ThematicMapWorldCitiesData("VAT_VATICAN_CITY","Vatican City",18));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_BRASILIA","Brasilia",43));
            s_dataList.add(new ThematicMapWorldCitiesData("RUS_SAMARA","Samara",69));
            s_dataList.add(new ThematicMapWorldCitiesData("LIE_VADUZ","Vaduz",32));
            s_dataList.add(new ThematicMapWorldCitiesData("PRT_LISBON","Lisbon",24));
            s_dataList.add(new ThematicMapWorldCitiesData("COL_CALI","Cali",52));
            s_dataList.add(new ThematicMapWorldCitiesData("TUR_ANKARA","Ankara",62));
            s_dataList.add(new ThematicMapWorldCitiesData("NCL_NOUMEA","Noumea",23));
            s_dataList.add(new ThematicMapWorldCitiesData("DNK_COPENHAGEN","Copenhagen",62));
            s_dataList.add(new ThematicMapWorldCitiesData("IND_DELHI","Delhi",73));
            s_dataList.add(new ThematicMapWorldCitiesData("GBR_GLASGOW","Glasgow",98));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_WASHINGTON","Washington",53));
            s_dataList.add(new ThematicMapWorldCitiesData("CAN_MONTREAL","Montreal",61));
            s_dataList.add(new ThematicMapWorldCitiesData("LAO_VIENTIANE","Vientiane",15));
            s_dataList.add(new ThematicMapWorldCitiesData("MCO_MONACO","Monaco",81));
            s_dataList.add(new ThematicMapWorldCitiesData("DZA_ORAN","Oran",83));
            s_dataList.add(new ThematicMapWorldCitiesData("CHN_CHONGQING","Chongqing",64));
            s_dataList.add(new ThematicMapWorldCitiesData("NPL_KATHMANDU","Kathmandu",26));
            s_dataList.add(new ThematicMapWorldCitiesData("BGD_DHAKA","Dhaka",22));
            s_dataList.add(new ThematicMapWorldCitiesData("EGY_CAIRO","Cairo",73));
            s_dataList.add(new ThematicMapWorldCitiesData("PRI_SAN_JUAN","San Juan",16));
            s_dataList.add(new ThematicMapWorldCitiesData("COD_KINSHASA","Kinshasa",25));
            s_dataList.add(new ThematicMapWorldCitiesData("GEO_TBILISI","Tbilisi",5));
            s_dataList.add(new ThematicMapWorldCitiesData("RWA_KIGALI","Kigali",79));
            s_dataList.add(new ThematicMapWorldCitiesData("SOM_MOGADISHU","Mogadishu",51));
            s_dataList.add(new ThematicMapWorldCitiesData("GBR_SAINT_HELIER","Saint Helier",38));
            s_dataList.add(new ThematicMapWorldCitiesData("GTM_GUATEMALA_CITY","Guatemala City",24));
            s_dataList.add(new ThematicMapWorldCitiesData("LBY_TRIPOLI","Tripoli",80));
            s_dataList.add(new ThematicMapWorldCitiesData("CHN_GUANGZHOU","Guangzhou",10));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_DETROIT","Detroit",2));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_PHILADELPHIA","Philadelphia",91));
            s_dataList.add(new ThematicMapWorldCitiesData("SLE_FREETOWN","Freetown",18));
            s_dataList.add(new ThematicMapWorldCitiesData("TTO_PORT_OF_SPAIN","Port of Spain",22));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_BALTIMORE","Baltimore",72));
            s_dataList.add(new ThematicMapWorldCitiesData("LUX_LUXEMBOURG","Luxembourg",5));
            s_dataList.add(new ThematicMapWorldCitiesData("GBR_MANCHESTER","Manchester",63));
            s_dataList.add(new ThematicMapWorldCitiesData("FRA_MARSEILLE","Marseille",72));
            s_dataList.add(new ThematicMapWorldCitiesData("CHE_BERNE","Berne",75));
            s_dataList.add(new ThematicMapWorldCitiesData("GNB_BISSAU","Bissau",41));
            s_dataList.add(new ThematicMapWorldCitiesData("GRL_NUUK","Nuuk",89));
            s_dataList.add(new ThematicMapWorldCitiesData("THA_BANGKOK","Bangkok",25));
            s_dataList.add(new ThematicMapWorldCitiesData("MDG_ANTANANARIVO","Antananarivo",10));
            s_dataList.add(new ThematicMapWorldCitiesData("ARE_ABU_DHABI","Abu Dhabi",59));
            s_dataList.add(new ThematicMapWorldCitiesData("SDN_KHARTOUM_UMM_DURMAN","Khartoum-Umm Durman",0));
            s_dataList.add(new ThematicMapWorldCitiesData("GIN_CONAKRY","Conakry",60));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_SAN_FRANCISCO","San Francisco",21));
            s_dataList.add(new ThematicMapWorldCitiesData("KGZ_BISHKEK","Bishkek",64));
            s_dataList.add(new ThematicMapWorldCitiesData("LTU_VILNIUS","Vilnius",68));
            s_dataList.add(new ThematicMapWorldCitiesData("NGA_KANO","Kano",48));
            s_dataList.add(new ThematicMapWorldCitiesData("POL_WARSAW","Warsaw",97));
            s_dataList.add(new ThematicMapWorldCitiesData("MYS_KUALA_LUMPUR","Kuala Lumpur",66));
            s_dataList.add(new ThematicMapWorldCitiesData("ISR_JERUSALEM","Jerusalem",53));
            s_dataList.add(new ThematicMapWorldCitiesData("GUF_CAYENNE","Cayenne",75));
            s_dataList.add(new ThematicMapWorldCitiesData("DZA_ALGIERS","Algiers",88));
            s_dataList.add(new ThematicMapWorldCitiesData("VNM_HO_CHI_MINH_CITY","Ho Chi Minh City",42));
            s_dataList.add(new ThematicMapWorldCitiesData("DOM_SANTO_DOMINGO","Santo Domingo",78));
            s_dataList.add(new ThematicMapWorldCitiesData("MAR_RABAT","Rabat",17));
            s_dataList.add(new ThematicMapWorldCitiesData("SRB_BELGRADE","Belgrade",95));
            s_dataList.add(new ThematicMapWorldCitiesData("PAK_ISLAMABAD","Islamabad",82));
            s_dataList.add(new ThematicMapWorldCitiesData("KAZ_ASTANA","Astana",56));
            s_dataList.add(new ThematicMapWorldCitiesData("NGA_KADUNA","Kaduna",10));
            s_dataList.add(new ThematicMapWorldCitiesData("GAB_LIBREVILLE","Libreville",13));
            s_dataList.add(new ThematicMapWorldCitiesData("CHN_TIANJIN","Tianjin",31));
            s_dataList.add(new ThematicMapWorldCitiesData("CHL_SANTIAGO","Santiago",35));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_BELO_HORIZONTE","Belo Horizonte",9));
            s_dataList.add(new ThematicMapWorldCitiesData("IND_NEW_DELHI","New Delhi",23));
            s_dataList.add(new ThematicMapWorldCitiesData("ECU_GUAYAQUIL","Guayaquil",57));
            s_dataList.add(new ThematicMapWorldCitiesData("MAC_MACAU","Macau",65));
            s_dataList.add(new ThematicMapWorldCitiesData("LVA_RIGA","Riga",24));
            s_dataList.add(new ThematicMapWorldCitiesData("EGY_ALEXANDRIA","Alexandria",98));
            s_dataList.add(new ThematicMapWorldCitiesData("SLB_HONIARA","Honiara",85));
            s_dataList.add(new ThematicMapWorldCitiesData("BWA_GABORONE","Gaborone",37));
            s_dataList.add(new ThematicMapWorldCitiesData("LBR_MONROVIA","Monrovia",35));
            s_dataList.add(new ThematicMapWorldCitiesData("SAU_RIYADH","Riyadh",57));
            s_dataList.add(new ThematicMapWorldCitiesData("SLV_SAN_SALVADOR","San Salvador",58));
            s_dataList.add(new ThematicMapWorldCitiesData("NGA_MAIDUGURI","Maiduguri",21));
            s_dataList.add(new ThematicMapWorldCitiesData("BRA_PORTO_ALEGRE","Porto Alegre",85));
            s_dataList.add(new ThematicMapWorldCitiesData("CAN_TORONTO","Toronto",77));
            s_dataList.add(new ThematicMapWorldCitiesData("CAN_OTTAWA","Ottawa",10));
            s_dataList.add(new ThematicMapWorldCitiesData("CMR_DOUALA","Douala",8));
            s_dataList.add(new ThematicMapWorldCitiesData("GBR_LONDON","London",24));
            s_dataList.add(new ThematicMapWorldCitiesData("BFA_OUAGADOUGOU","Ouagadougou",93));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_HOUSTON","Houston",71));
            s_dataList.add(new ThematicMapWorldCitiesData("ESP_BARCELONA","Barcelona",44));
            s_dataList.add(new ThematicMapWorldCitiesData("DEU_HAMBURG","Hamburg",63));
            s_dataList.add(new ThematicMapWorldCitiesData("IRQ_BAGHDAD","Baghdad",18));
            s_dataList.add(new ThematicMapWorldCitiesData("LSO_MASERU","Maseru",23));
            s_dataList.add(new ThematicMapWorldCitiesData("ROC_TAIPEI","Taipei",82));
            s_dataList.add(new ThematicMapWorldCitiesData("USA_ST__LOUIS","St. Louis",85));
            s_dataList.add(new ThematicMapWorldCitiesData("CZE_PRAGUE","Prague",81));
            s_dataList.add(new ThematicMapWorldCitiesData("MKD_SKOPJE","Skopje",97));
            s_dataList.add(new ThematicMapWorldCitiesData("SGP_SINGAPORE","Singapore",88));
            s_dataList.add(new ThematicMapWorldCitiesData("ZAF_DURBAN","Durban",78));
            s_dataList.add(new ThematicMapWorldCitiesData("IND_KOLKATA","Kolkata",93));
            s_dataList.add(new ThematicMapWorldCitiesData("CRI_SAN_JOSE","San Jose",82));
            s_dataList.add(new ThematicMapWorldCitiesData("BTN_THIMPHU","Thimphu",37));
            s_dataList.add(new ThematicMapWorldCitiesData("NGA_LAGOS","Lagos",1));
            s_dataList.add(new ThematicMapWorldCitiesData("ETH_ADDIS_ABABA","Addis Ababa",98));
        }
    }

    public List<ThematicMapWorldCitiesData> getThematicMapWorldCitiesData() {
        return s_dataList;
    }

    public int getThematicMapWorldCitiesDataCount() {
        return s_dataList.size();
    }
}
