package oracle.adfmf.demo.push.model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 24 22:48:53 PST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegistrationModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RegistrationModuleImpl() {
    }

    /**
     * Container's getter for RegistrationsView1.
     * @return RegistrationsView1
     */
    public ViewObjectImpl getRegistrationsView1() {
        return (ViewObjectImpl)findViewObject("RegistrationsView1");
    }

    /**
     * Container's getter for TokensView1.
     * @return TokensView1
     */
    public ViewObjectImpl getTokensView1() {
        return (ViewObjectImpl)findViewObject("TokensView1");
    }

    /**
     * Container's getter for TokensView2.
     * @return TokensView2
     */
    public ViewObjectImpl getTokensView2() {
        return (ViewObjectImpl)findViewObject("TokensView2");
    }

    /**
     * Container's getter for TokensRegistrationsFk1Link1.
     * @return TokensRegistrationsFk1Link1
     */
    public ViewLinkImpl getTokensRegistrationsFk1Link1() {
        return (ViewLinkImpl)findViewLink("TokensRegistrationsFk1Link1");
    }
}
